on:
  workflow_dispatch:
  schedule:
    # 매일 한국시간 00:22 실행
    # KST 00:22 = UTC 전날 15:22
    - cron: "22 15 * * *"

jobs:
  r:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: python3 -m pip install -r requirements.txt
      - run: python3 main.py
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          SOURCE_DB_ID: ${{ secrets.SOURCE_DB_ID }}
          TARGET_DB_ID: ${{ secrets.TARGET_DB_ID }}
