on: workflow_dispatch
jobs:
  r:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: python3 main.py
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          SOURCE_DB_ID: ${{ secrets.SOURCE_DB_ID }}
          TARGET_DB_ID: ${{ secrets.TARGET_DB_ID }}
